import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Notifications from "@/components/Notification/Notification";
import QueryProvider from "@/components/QueryProvider/QueryProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: '400'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <QueryProvider>
          {children}
          <Notifications />
        </QueryProvider>
      </body>
    </html>
  );
}
